language: node_js
node_js: node

cache:
  directories:
    - node_modules
    - public

install:
  - npm i

script:
  - npm test
  - npm run build

after_success:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - npm run deploy

notifications:
    email: false
    slack: kremalicious:LXLUCjkY5yaZaC9vHl9vIORr
