sudo: false
language: ruby
rvm:
    - 1.9.3
cache: bundler
addons:
    apt:
        packages:
            - libgsl0-dev
before_script:
    - npm install gulp bower -g
    - npm install
    - bower install
    - bundle install
script: gulp build
