dist: xenial
language: node_js
node_js:
  - '11'

git:
  depth: 10

cache:
  directories:
    - node_modules
    - public

# will run `npm install` automatically here

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install python3-pip
  - sudo -H pip3 install --upgrade pip

script:
  - npm test
  - travis_wait 60 npm run build

after_success:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - npm run deploy

notifications:
  email: false
  slack: kremalicious:LXLUCjkY5yaZaC9vHl9vIORr
