sudo: required
dist: trusty

language: ruby
rvm:
    - 2.4

cache:
  bundler: true
  directories:
  - $TRAVIS_BUILD_DIR/node_modules
  - $TRAVIS_BUILD_DIR/_site/media

addons:
    artifacts:
        paths:
        - $TRAVIS_BUILD_DIR/_site/media
    apt:
        packages:
        - libgsl0ldbl
        - libgsl0-dev

before_install:
    - nvm install 8

before_script: "_ci/setup.sh"
script: "_ci/build.sh"

deploy:
  skip_cleanup: true
  provider: script
  script: "_ci/deploy.sh"
  on:
    branch: master


notifications:
    email: false
    slack: kremalicious:LXLUCjkY5yaZaC9vHl9vIORr
