language: node_js
node_js: node

cache:
  directories:
    - node_modules
    - public

install:
  - npm install -g scrypt
  - npm i
  - ln -s ./node_modules/scrypt /usr/local/lib/node_modules/scrypt/build

script:
  - npm test
  - travis_wait 60 npm run build

after_success:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - npm run deploy

notifications:
  email: false
  slack: kremalicious:LXLUCjkY5yaZaC9vHl9vIORr
