language: node_js
node_js: node

cache:
  directories:
    - node_modules
    - public

compiler:
  - gcc
  - clang

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang

install:
  - npm i

script:
  - npm test
  - travis_wait 60 npm run build

after_success:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - npm run deploy

notifications:
  email: false
  slack: kremalicious:LXLUCjkY5yaZaC9vHl9vIORr
