#
# Home:                 /
# About Page:           /about/
# Archive Page:         /archive/
# Pagination:           /page/N/
# Post:                 /post-slug/
# RSS Feed:             /feed/
#

# Basics
# --------------------

name:                   kremalicious
description:            'Blog of designer & developer Matthias Kretschmann'
url:                    https://kremalicious.com
author:
    name:               Matthias Kretschmann
    email:              m@kretschmann.io
    uri:                https://kretschmann.io
    twitter:            kremalicious
    facebook:           matthiaskretschmann
    googleplus:         +MatthiasKretschmann
    bitcoin:            171qDmKEXm9YBgBLXyGjjPvopP5o9htQ1V


# Urls
# --------------------

permalink:              /:title/
paginate:               15
paginate_path:          "/page/:num"
category_dir:           "/"
category_title_prefix:  ""
media_url:              "https://res.cloudinary.com/kremalicious"


# Content Parsing
# --------------------

future:                 false
markdown:               redcarpet

redcarpet:
    extensions:         ['no_intra_emphasis', 'autolink', 'tables', 'smart', 'hard_wrap', 'fenced_code_blocks', 'strikethrough', 'highlight', 'quote', 'footnotes', 'with_toc_data', 'space_after_headers', 'superscript', 'lax_spacing']


# Generator
# --------------------

source:                 ./_src
destination:            ./_site
keep_files:             ['media']


# Plugins
# --------------------

gems:
    - jekyll-sitemap
    - jekyll-redirect-from
    - jekyll-paginate
    - jekyll-archives


# jekyll-archives
# --------------------

jekyll-archives:
    enabled:
        - categories
        - tags
    layout: 'archive'
    permalinks:
        tag: '/tag/:name/'
        category: '/:name/'


# jekyll-picture-tag
# --------------------

picture:
  source: "_media"
  output: "media/gen"
  markup: "picture"
  presets:
    default:
      ppi: [1, 2]
      source_large:
        media: "(min-width: 87.500em)"
        width: "1000"
      source_medium:
        media: "(min-width: 40.625em)"
        width: "800"
      source_small:
        media: "(min-width: 30em)"
        width: "600"
      source_default:
        width: "400"
    phototeaser:
      ppi: [1, 2]
      source_large:
        media: "(min-width: 87.500em)"
        width: "1000"
        height: "650"
      source_medium:
        media: "(min-width: 40.625em)"
        width: "800"
        height: "550"
      source_small:
        media: "(min-width: 30em)"
        width: "600"
        height: "450"
      source_default:
        width: "400"
        height: "250"
    featured:
      ppi: [1, 2]
      attr:
        class: "featured-image"
        itemprop: "image"
      source_medium:
        media: "(min-width: 40.625em)"
        width: "275"
        height: "100"
      source_default:
        width: "190"
        height: "100"
    photothumb:
      ppi: [1, 2]
      attr:
        class: "related-image"
        itemprop: "image"
      source_default:
        width: "190"
        height: "190"
