#
# Home:                 /
# About Page:           /about/
# Archive Page:         /archive/
# Pagination:           /page/N/
# Post:                 /post-slug/
# RSS Feed:             /feed/
#

# Basics
# --------------------

name:                   kremalicious
description:            'Blog of designer & developer Matthias Kretschmann'
url:                    https://kremalicious.com
author:
    name:               Matthias Kretschmann
    email:              m@kretschmann.io
    uri:                http://kretschmann.io


# Urls
# --------------------

permalink:              /:title/
paginate:               15
paginate_path:          "/page/:num"
category_dir:           "/"
category_title_prefix:  ""


# Content Parsing
# --------------------

future:                 false
markdown:               redcarpet
highlighter:            rouge

redcarpet:
    extensions:         ['autolink', 'smart', 'hard_wrap']


# Generator
# --------------------

source:                 ./_src
destination:            ./_site
keep_files:             ['media', 'gen']


# Plugins
# --------------------

gems:
    - jekyll-sitemap
    - jekyll-redirect-from
    - jekyll-picture-tag
    - jekyll-archives

# jekyll-picture-tag
# --------------------

picture:
  source: "_media"
  output: "media/gen"
  markup: "picture"
  presets:
    default:
      ppi: [1, 2]
      attr:
        itemprop: "image"
      source_medium:
        media: "(min-width: 35.556em)"
        width: "640"
      source_small:
        media: "(min-width: 26.667em)"
        width: "480"
      source_default:
        width: "320"
    featured:
      ppi: [1, 2]
      attr:
        class: "featured-image"
        itemprop: "image"
      source_default:
        width: "190"
