# 
# Home:             /
# About Page:       /about/
# Archive Page:     /archive/
# Pagination:       /page/N/
# Post:             /post/post-slug/
# RSS Feed:         /feed.xml
# 

# Basics
# --------------------

name: kremalicious
description: 'Blog of designer & developer Matthias Kretschmann'
url: http://kremalicious.com
author: Matthias Kretschmann


# Urls
# --------------------

permalink: /post/:title
relative_permalinks: true
paginate: 10
paginate_path: "/page/:num"


# Content Parsing
# --------------------

markdown: redcarpet  
pygments: true


# Generator
# --------------------

source:      ./_src
destination: ./_site
exclude:     ['design', 'node_modules', 'less']
keep_files:  ['media', 'gen']


# jekyll-picture-tag
# --------------------

picture:
  source: "_media"
  output: "media/gen"
  markup: "picturefill"
  presets:
    default:
      ppi: [1, 1.5, 2]
      attr:
        itemprop: "image"
      source_medium:
        media: "(min-width: 35.556em)"
        width: "640"
      source_small:
        media: "(min-width: 26.667em)"
        width: "480"
      source_default: 
        width: "320"
    featured:
      ppi: [1, 1.5, 2]
      attr:
        class: "featured-image"
        itemprop: "image"
      source_default: 
        width: "190"