#
# Home:                 /
# Archive Page:         /archive/
# Pagination:           /page/N/
# Post:                 /post-slug/
# RSS Feed:             /feed/
#

# Basics
# --------------------

title:                  kremalicious
tagline:                'Blog of designer & developer Matthias Kretschmann'
url:                    https://kremalicious.com
author:
    name:               Matthias Kretschmann
    email:              m@kretschmann.io
    uri:                https://matthiaskretschmann.com
    twitter:            https://twitter.com/kremalicious
    github:             https://github.com/kremalicious
    facebook:           https://facebook.com/matthiaskretschmann
    googleplus:         https://plus.google.com/+MatthiasKretschmann
    rss:                https://kremalicious.com/feed.xml
    jsonfeed:           http://kremalicious.com/feed.json
    avatar:             ../src/images/avatar.jpg
    bitcoin:            171qDmKEXm9YBgBLXyGjjPvopP5o9htQ1V
    ether:              "0x339dbC44d39bf1961E385ed0Ae88FC6069b87Ea1"


typekitID:              msu4qap
itemsPerPage:           15
